
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 3
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    #define yy_create_buffer yy_create_buffer

    #define yy_delete_buffer yy_delete_buffer

    #define yy_scan_buffer yy_scan_buffer

    #define yy_scan_string yy_scan_string

    #define yy_scan_bytes yy_scan_bytes

    #define yy_init_buffer yy_init_buffer

    #define yy_flush_buffer yy_flush_buffer

    #define yy_load_buffer_state yy_load_buffer_state

    #define yy_switch_to_buffer yy_switch_to_buffer

    #define yypush_buffer_state yypush_buffer_state

    #define yypop_buffer_state yypop_buffer_state

    #define yyensure_buffer_stack yyensure_buffer_stack

    #define yylex yylex

    #define yyrestart yyrestart

    #define yylex_init yylex_init

    #define yylex_init_extra yylex_init_extra

    #define yylex_destroy yylex_destroy

    #define yyget_debug yyget_debug

    #define yyset_debug yyset_debug

    #define yyget_extra yyget_extra

    #define yyset_extra yyset_extra

    #define yyget_in yyget_in

    #define yyset_in yyset_in

    #define yyget_out yyget_out

    #define yyset_out yyset_out

    #define yyget_leng yyget_leng

    #define yyget_text yyget_text

    #define yyget_lineno yyget_lineno

    #define yyset_lineno yyset_lineno

    #define yywrap yywrap

    #define yyalloc yyalloc

    #define yyrealloc yyrealloc

    #define yyfree yyfree

    #define yytext yytext

    #define yyleng yyleng

    #define yyin yyin

    #define yyout yyout

    #define yy_flex_debug yy_flex_debug

    #define yylineno yylineno

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 115
#define YY_END_OF_BUFFER 116
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[405] =
    {   0,
        0,    0,  116,  114,  112,  113,  100,  114,    2,  106,
       99,  114,   94,   95,  104,  103,   91,  102,   98,  105,
       56,   55,   92,   88,  107,   93,  108,  111,   53,   53,
       96,   97,  109,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   89,
      110,   90,  101,  112,   87,    0,   64,    0,    0,   73,
       90,   82,   74,    0,    0,   71,   79,   69,   80,   70,
       81,    0,   59,    1,    3,   72,   60,   56,    0,    0,
       56,   56,    0,   56,   55,   55,   55,   55,   97,   89,
        0,   96,   78,   84,   65,   86,   85,   77,   53,    0,

        0,   75,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   13,   53,
       53,   53,   53,   53,   53,   53,   22,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       76,   83,   64,    0,    0,    0,    0,    0,   57,    0,
        0,   66,    0,   59,    3,    0,   60,    0,   58,   56,
       56,   56,   56,    0,   54,   55,   55,   55,   55,   68,
       67,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   20,   53,   53,   24,   53,   53,

       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,    0,    0,    0,    0,    0,
        0,   59,    0,   60,   58,   56,    0,    0,   54,    0,
       54,   54,   55,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,    5,    6,   53,    8,    9,   53,   53,
       53,   53,   15,   16,   53,   53,   53,   21,   53,   25,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   35,
       53,   53,   53,   39,   53,   53,    0,    0,    0,    0,
        0,    0,    0,   54,   54,    0,   61,   54,   54,   53,
       53,   45,   53,   53,   53,   53,   53,   53,   53,    7,

       10,   53,   53,   53,   53,   18,   19,   53,   53,   53,
       53,   29,   53,   53,   53,   53,   53,   53,   37,   53,
       53,   41,    0,    0,   62,    0,   63,   61,   54,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       14,   17,   23,   53,   53,   28,   30,   31,   32,   33,
       34,   53,   53,   53,    0,   62,   63,   53,   53,   44,
       53,   53,   53,   53,   53,   53,   53,   53,   12,   53,
       53,   36,   53,   53,    4,   42,   43,   46,   47,   53,
       53,   53,   53,   52,   11,   26,   27,   38,   40,   53,
       49,   53,   53,   48,   53,   53,   53,   53,   53,   53,

       53,   51,   50,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   35,   35,   37,   35,   38,   35,   39,
       35,   35,   40,   41,   42,   35,   35,   43,   35,   35,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   35,   58,   59,   60,   61,
       62,   63,   35,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[77] =
    {   0,
        1,    1,    2,    1,    3,    1,    4,    1,    5,    1,
        1,    1,    1,    1,    1,    6,    1,    7,    7,    8,
        8,    4,    1,    4,    4,    4,    3,    9,    9,    9,
        9,    9,    9,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,    1,    3,    1,    1,   11,   12,   12,
        9,    9,    9,   12,   10,   10,   10,   10,   10,   10,
       13,   10,   10,   13,   10,   13,   10,   13,   10,   13,
       10,   10,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[416] =
    {   0,
        0,    0,  747,  748,  744,  748,  720,   72,  687,   53,
       72,  698,  748,  748,  717,   68,  748,   69,   67,   79,
      102,   82,  715,  748,   83,  715,   85,  748,    0,  107,
      748,  748,  714,  102,  671,   51,   97,   75,   93,   98,
      675,   28,  674,  682,  108,   28,  153,  672,  677,  748,
      101,  748,  748,  730,  748,  122,  146,  152,  670,  748,
      748,  748,  748,  147,  160,  748,  748,  748,  748,  748,
      748,  714,  166,  748,    0,  748,  175,  217,  224,  242,
      139,  131,  713,  138,  232,  174,  145,  159,  748,  748,
      264,  748,  703,  748,  748,  748,  748,  702,    0,  186,

      681,  748,  143,  663,  662,  670,  662,  659,  654,  663,
      664,  651,  654,  662,  649,  664,  651,  657,  643,  644,
      641,  641,  647,  643,  640,  637,    0,  151,  641,  213,
      639,  160,  175,  643,  632,  635,  692,   68,  164,  639,
      748,  748,  270,  690,  253,  275,    0,  643,  748,  278,
        0,  748,  285,  748,    0,  295,  748,  306,  310,  225,
      748,  656,  633,    0,  303,  267,  748,  654,  631,  748,
      748,  632,  626,  625,  626,  624,  635,  619,  633,  617,
      613,  617,  619,  628,  623,  611,  181,  625,  623,  619,
      611,  617,  604,  619,    0,  604,  608,    0,  605,  602,

      588,  586,  584,  586,  578,  561,  559,  559,  571,  569,
      558,  559,  563,  565,  554,  330,  371,  552,  332,  417,
      334,  360,  338,  421,  748,  748,  283,  297,  296,  392,
      258,  329,  748,  554,  538,  536,  531,  539,  527,  526,
      500,  510,  501,    0,    0,  503,    0,    0,  494,  501,
      490,  497,    0,    0,  491,  501,  487,    0,  491,    0,
      486,  486,  485,  482,  494,  484,  488,  493,  492,    0,
      488,  478,  482,    0,  468,  480,  276,    0,  465,  256,
        0,  463,  472,  319,  748,  364,  476,  494,  470,  467,
      470,    0,  463,  457,  463,  452,  460,  467,  463,    0,

        0,  451,  452,  457,  447,    0,    0,  454,  440,  448,
      443,    0,  447,  444,  438,  422,  430,  426,    0,  416,
      417,    0,  421,  409,  482,  413,  505,  748,  748,  325,
      421,  412,  407,  402,  394,  409,  407,  409,  389,  389,
        0,    0,    0,  400,  401,    0,    0,    0,    0,    0,
        0,  397,  391,  384,  365,  748,  748,  352,  361,    0,
      339,  357,  357,  334,  347,  346,  325,  319,    0,  304,
      301,    0,  313,  291,  748,    0,    0,    0,    0,  275,
      271,  269,  252,    0,    0,    0,    0,    0,    0,  231,
        0,  218,  220,    0,  201,  176,  147,  140,  102,   70,

       40,    0,    0,  748,  564,  577,  587,  594,  605,  616,
      629,  637,  643,  649,  655
    } ;

static const flex_int16_t yy_def[416] =
    {   0,
      404,    1,  404,  404,  404,  404,  404,  405,  404,  404,
      404,  406,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  407,  404,  404,  404,  408,  408,
      404,  404,  404,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  404,
      404,  404,  404,  404,  404,  405,  404,  409,  404,  404,
      404,  404,  404,  406,  410,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  411,  404,  404,  404,  404,  404,
      404,  404,  412,  404,  404,  404,  404,  404,  404,  404,
      407,  404,  404,  404,  404,  404,  404,  404,  408,  405,

      406,  404,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      404,  404,  404,  404,  404,  405,  413,  404,  404,  406,
      414,  404,  404,  404,  411,  404,  404,  404,  404,  404,
      404,  404,  404,  415,  412,  404,  404,  404,  404,  404,
      404,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  405,  405,  404,  406,  406,
      404,  404,  404,  404,  404,  404,  415,  415,  404,  404,
      404,  404,  404,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  405,  217,  404,  406,
      220,  404,  404,  404,  404,  404,  404,  404,  404,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  404,  404,  404,  404,  404,  404,  404,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  404,  404,  404,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  404,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,    0,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404
    } ;

static const flex_int16_t yy_nxt[825] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   30,   29,   29,   29,
       29,   30,   29,   31,    4,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   29,   42,   29,   43,   29,
       29,   29,   29,   44,   45,   46,   47,   48,   49,   29,
       29,   29,   50,   51,   52,   53,   57,   60,   61,   62,
       67,  127,   72,   69,   73,   73,   73,   73,  128,   90,
       74,  135,   68,   70,   71,   75,   63,   77,  136,   85,

       85,   85,   85,   76,   92,  403,   93,   94,   95,   97,
       98,  100,  113,   80,  114,  101,   58,   77,   86,   78,
       78,   79,   79,   87,  211,  141,   57,  118,  402,  103,
      104,  105,  212,   80,   80,  106,  119,  107,   81,  108,
       88,  109,  110,   82,   83,  115,  123,  143,   87,  111,
      100,  120,  116,  121,   80,  149,  124,  100,  117,  125,
       84,  101,  122,  131,  132,  401,   58,  162,   82,  146,
      146,   83,  137,  133,  142,  160,  134,  150,  150,  161,
      161,  168,  144,   73,   73,   73,   73,  144,  400,  163,
       57,   65,   73,   73,   73,   73,  160,  153,  154,  399,

      167,  172,  154,  169,  161,  161,  156,  157,  173,  197,
      166,  157,  145,  138,  204,  167,  198,  166,  153,  154,
      213,  147,  214,  206,  154,  167,  398,  156,  157,  151,
       58,  205,   77,  157,   78,   78,   79,   79,  207,   77,
      167,   79,   79,   79,   79,  249,  250,   77,   80,   85,
       85,   85,   85,   81,  158,   80,  158,  100,   82,  159,
      159,  159,  159,   80,  149,  397,  161,  200,   86,   80,
      404,  143,  144,   87,  100,   84,   80,  201,  202,   57,
       57,  396,  395,   82,   80,  404,  149,  404,  404,   95,
       88,  161,  216,  216,  288,  219,  219,  221,   87,  221,

       65,  394,  222,  222,  222,  222,  144,  223,  167,  223,
      393,  144,  224,  224,  224,  224,  289,  392,  228,   58,
       58,  282,   65,  159,  159,  159,  159,  159,  159,  159,
      159,  391,  284,  167,   57,  283,  145,  285,  390,  229,
      149,  230,  225,  389,  231,  282,  225,  277,  277,  280,
      280,  222,  222,  222,  222,  224,  224,  224,  224,  283,
      285,  232,  285,  225,  388,  230,  387,  386,  225,  231,
      285,  385,  384,  358,   58,   57,   65,  222,  222,  222,
      222,  287,  287,  287,  287,  285,  359,  284,  278,  278,
      278,  278,  154,  383,  382,  285,  154,  381,  278,  278,

      278,  278,  278,  278,  286,  380,  286,  379,  378,  287,
      287,  287,  287,  154,  377,   58,  376,  375,  154,  278,
      278,  278,  278,  278,  278,  149,  325,  325,  325,  325,
      327,  327,  327,  327,  281,  281,  281,  281,  224,  224,
      224,  224,  374,  373,  281,  281,  281,  281,  281,  281,
      372,  371,  370,  157,  369,  368,  367,  157,  366,  365,
      364,   65,  363,  362,  361,  281,  281,  281,  281,  281,
      281,  360,  355,  354,  157,  324,  353,  324,  352,  157,
      325,  325,  325,  325,  326,  351,  326,  350,  349,  327,
      327,  327,  327,  287,  287,  287,  287,  348,  347,  325,

      325,  325,  325,  346,  345,  344,  343,  342,  328,  341,
      340,  339,  328,  338,  356,  337,  336,  335,  356,  334,
      333,  332,  327,  327,  327,  327,  331,  330,  329,  328,
      329,  323,  322,  321,  328,  356,  320,  357,  319,  318,
      356,  357,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  304,  303,  302,  357,  301,
      300,  299,  298,  357,   56,  297,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   64,  296,   64,
       64,  295,   64,   64,   64,   64,   64,   64,   64,   64,
       91,  294,   91,  293,  292,   91,   91,  291,   91,   91,

       99,   99,   99,   99,   99,   99,   99,   56,  290,   56,
      279,   56,  276,  275,  274,  273,   56,   56,   64,  272,
       64,  271,   64,  270,  269,  268,  267,   64,   64,  155,
      266,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  165,  165,  165,  165,  265,  264,  165,  217,
      217,  217,  263,  262,  217,  220,  220,  220,  261,  260,
      220,  227,  227,  227,  259,  258,  227,  257,  256,  255,
      254,  253,  252,  251,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,
      233,  226,  226,  218,  100,  215,  100,  210,  209,  208,

      203,  199,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,   65,  171,  170,  164,  152,
      148,   54,  140,  139,  130,  129,  126,  112,  102,   96,
       89,   66,   65,   59,   55,   54,  404,    3,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,

      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404
    } ;

static const flex_int16_t yy_chk[825] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,   10,   10,   11,
       16,   42,   19,   18,   19,   19,   19,   19,   42,   25,
       20,   46,   16,   18,   18,   20,   11,   22,   46,   22,

       22,   22,   22,   20,   25,  401,   25,   25,   25,   27,
       27,   30,   36,   22,   36,   30,    8,   21,   22,   21,
       21,   21,   21,   22,  138,   51,   56,   38,  400,   34,
       34,   34,  138,   21,   22,   34,   38,   34,   21,   34,
       22,   34,   34,   21,   21,   37,   40,   57,   22,   34,
       57,   39,   37,   39,   21,   64,   40,   47,   37,   40,
       21,   47,   39,   45,   45,  399,   56,   82,   21,   58,
       58,   21,   47,   45,   51,   81,   45,   65,   65,   84,
       81,   87,   57,   73,   73,   73,   73,   57,  398,   82,
      100,   64,   77,   77,   77,   77,   84,   73,   73,  397,

       88,  103,   73,   87,   84,   81,   77,   77,  103,  128,
       86,   77,   57,   47,  132,   86,  128,   88,   73,   73,
      139,   58,  139,  133,   73,   88,  396,   77,   77,   65,
      100,  132,   78,   77,   78,   78,   78,   78,  133,   79,
       86,   79,   79,   79,   79,  187,  187,   85,   78,   85,
       85,   85,   85,   78,   80,   79,   80,  145,   78,   80,
       80,   80,   80,   85,  280,  395,  160,  130,   85,   78,
       91,  143,  145,   85,  143,   78,   79,  130,  130,  146,
      277,  393,  392,   78,   85,   91,  150,   91,   91,   91,
       85,  160,  146,  146,  231,  150,  150,  153,   85,  153,

      280,  390,  153,  153,  153,  153,  143,  156,  166,  156,
      383,  143,  156,  156,  156,  156,  231,  382,  165,  146,
      277,  227,  150,  158,  158,  158,  158,  159,  159,  159,
      159,  381,  229,  166,  216,  228,  143,  229,  380,  165,
      219,  165,  159,  374,  165,  227,  159,  216,  216,  219,
      219,  221,  221,  221,  221,  223,  223,  223,  223,  228,
      284,  165,  229,  159,  373,  165,  371,  370,  159,  165,
      232,  368,  367,  330,  216,  217,  219,  222,  222,  222,
      222,  286,  286,  286,  286,  284,  330,  232,  217,  217,
      217,  217,  222,  366,  365,  232,  222,  364,  217,  217,

      217,  217,  217,  217,  230,  363,  230,  362,  361,  230,
      230,  230,  230,  222,  359,  217,  358,  355,  222,  217,
      217,  217,  217,  217,  217,  220,  324,  324,  324,  324,
      326,  326,  326,  326,  220,  220,  220,  220,  224,  224,
      224,  224,  354,  353,  220,  220,  220,  220,  220,  220,
      352,  345,  344,  224,  340,  339,  338,  224,  337,  336,
      335,  220,  334,  333,  332,  220,  220,  220,  220,  220,
      220,  331,  323,  321,  224,  282,  320,  282,  318,  224,
      282,  282,  282,  282,  283,  317,  283,  316,  315,  283,
      283,  283,  283,  287,  287,  287,  287,  314,  313,  325,

      325,  325,  325,  311,  310,  309,  308,  305,  287,  304,
      303,  302,  287,  299,  325,  298,  297,  296,  325,  295,
      294,  293,  327,  327,  327,  327,  291,  290,  289,  287,
      288,  279,  276,  275,  287,  325,  273,  327,  272,  271,
      325,  327,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  259,  257,  256,  255,  252,  251,  250,  327,  249,
      246,  243,  242,  327,  405,  241,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  406,  240,  406,
      406,  239,  406,  406,  406,  406,  406,  406,  406,  406,
      407,  238,  407,  237,  236,  407,  407,  235,  407,  407,

      408,  408,  408,  408,  408,  408,  408,  409,  234,  409,
      218,  409,  215,  214,  213,  212,  409,  409,  410,  211,
      410,  210,  410,  209,  208,  207,  206,  410,  410,  411,
      205,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  412,  412,  412,  412,  204,  203,  412,  413,
      413,  413,  202,  201,  413,  414,  414,  414,  200,  199,
      414,  415,  415,  415,  197,  196,  415,  194,  193,  192,
      191,  190,  189,  188,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  169,
      168,  163,  162,  148,  144,  140,  137,  136,  135,  134,

      131,  129,  126,  125,  124,  123,  122,  121,  120,  119,
      118,  117,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  105,  104,  101,   98,   93,   83,   72,
       59,   54,   49,   48,   44,   43,   41,   35,   33,   26,
       23,   15,   12,    9,    7,    5,    3,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,

      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cl.l"
#line 18 "cl.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cp.tab.h"
#include "inc.h"

extern node *currnode;
extern node *prev;

extern void yyerror(const char *);  /* prints grammar violation message */
extern int sym_type(const char *);  /* returns type from symbol table */

#define sym_type(identifier) IDENTIFIER /* with no symbol table, fake it */

extern locnode *init;

static void comment(void);
static void prep(void);
static int check_type(void);
#line 854 "lex.yy.c"
#line 855 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 40 "cl.l"

#line 1074 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 405 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 748 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "cl.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "cl.l"
{ prep(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "cl.l"
{ /* consume //-comment */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "cl.l"
{ Node("include ","INCLUDE"); return(INCLUDE);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "cl.l"
{ Node("auto ","AUTO"); return(AUTO); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "cl.l"
{ Node("bool ", "BOOL"); return(BOOL); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 47 "cl.l"
{ Node("break ","BREAK"); return(BREAK); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 48 "cl.l"
{ Node("case ","CASE"); return(CASE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "cl.l"
{ Node("char ","CHAR"); return(CHAR); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "cl.l"
{ Node("const ","CONST"); return(CONST); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "cl.l"
{ Node("continue ","CONTINUE"); return(CONTINUE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "cl.l"
{ Node("default ","DEFAULT"); return(DEFAULT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "cl.l"
{ Node("do ","DO"); return(DO); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "cl.l"
{ Node("double ","DOUBLE"); return(DOUBLE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "cl.l"
{ Node("else ","ELSE"); return(ELSE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "cl.l"
{ Node("enum ","ENUM"); return(ENUM); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "cl.l"
{ Node("extern ","EXTERN"); return(EXTERN); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "cl.l"
{ Node("false ", "FALSEVAL"); return(FALSEVAL);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "cl.l"
{ Node("float ","FLOAT"); return(FLOAT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "cl.l"
{ Node("for ","FOR"); return(FOR); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "cl.l"
{ Node("goto ","GOTO"); return(GOTO); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "cl.l"
{ Node("if ","IF"); return(IF); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "cl.l"
{ Node("inline ","INLINE"); return(INLINE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "cl.l"
{ Node("int ","INT"); return(INT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "cl.l"
{ Node("long ","LONG"); return(LONG); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "cl.l"
{ Node("register ","REGISTER"); return(REGISTER); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "cl.l"
{ Node("restrict ","RESTRICT"); return(RESTRICT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "cl.l"
{ Node("return ","RETURN"); return(RETURN); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "cl.l"
{ Node("short ","SHORT"); return(SHORT); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 70 "cl.l"
{ Node("signed ","SIGNED"); return(SIGNED); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "cl.l"
{ Node("sizeof ","SIZEOF"); return(SIZEOF); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "cl.l"
{ Node("static ","STATIC"); return(STATIC); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "cl.l"
{ Node("struct ","STRUCT"); return(STRUCT); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "cl.l"
{ Node("switch ","SWITCH"); return(SWITCH); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "cl.l"
{ Node("true ", "TRUEVAL"); return(TRUEVAL); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "cl.l"
{ Node("typedef ","TYPEDEF"); return(TYPEDEF); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "cl.l"
{ Node("union ","UNION"); return(UNION); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "cl.l"
{ Node("unsigned ","UNSIGNED"); return(UNSIGNED); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "cl.l"
{ Node("void ","VOID"); return(VOID); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "cl.l"
{ Node("volatile ","VOLATILE"); return(VOLATILE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "cl.l"
{ Node("while ","WHILE"); return(WHILE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "cl.l"
{ Node("alignas ","ALIGNAS"); return ALIGNAS; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "cl.l"
{ Node("alignof ","ALIGNOF"); return ALIGNOF; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "cl.l"
{ Node("atomic ","ATOMIC"); return ATOMIC; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "cl.l"
{ Node("bool ","BOOL"); return BOOL; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "cl.l"
{ Node("complex ","COMPLEX"); return COMPLEX; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "cl.l"
{ Node("generic ","GENERIC"); return GENERIC; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "cl.l"
{ Node("imaginary ","IMAGINARY"); return IMAGINARY; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "cl.l"
{ Node("noreturn ","NORETURN"); return NORETURN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "cl.l"
{ Node("static ","STATIC_ASSERT"); return STATIC_ASSERT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 91 "cl.l"
{ Node("thread ","THREAD_LOCAL"); return THREAD_LOCAL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "cl.l"
{ Node("func ","FUNC_NAME"); return FUNC_NAME; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 94 "cl.l"
{ return check_type(); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "cl.l"
{ Node(yytext,"I_CONSTANT"); return I_CONSTANT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "cl.l"
{ Node(yytext,"I_CONSTANT"); return I_CONSTANT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "cl.l"
{ Node(yytext,"I_CONSTANT"); return I_CONSTANT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "cl.l"
{ Node(yytext,"I_CONSTANT"); return I_CONSTANT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 "cl.l"
{ Node(yytext,"F_CONSTANT"); return F_CONSTANT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 102 "cl.l"
{ Node(yytext,"F_CONSTANT"); return F_CONSTANT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 "cl.l"
{ Node(yytext,"F_CONSTANT"); return F_CONSTANT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "cl.l"
{ Node(yytext,"F_CONSTANT"); return F_CONSTANT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "cl.l"
{ Node(yytext,"F_CONSTANT"); return F_CONSTANT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "cl.l"
{ Node(yytext,"F_CONSTANT"); return F_CONSTANT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 108 "cl.l"
{Node(yytext,"STRING_LITERAL"); return STRING_LITERAL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 109 "cl.l"
{Node(yytext,"STD_LIBRARY"); return STD_LIBRARY; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 111 "cl.l"
{ Node("... ","ELLIPSIS"); return ELLIPSIS; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 112 "cl.l"
{ Node(">>= ","RIGHT_ASSIGN"); return RIGHT_ASSIGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 113 "cl.l"
{ Node("<<= ","LEFT_ASSIGN"); return LEFT_ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 114 "cl.l"
{ Node("+= ","ADD_ASSIGN"); return ADD_ASSIGN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 115 "cl.l"
{ Node("-= ","SUB_ASSIGN"); return SUB_ASSIGN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "cl.l"
{ Node("*= ","MUL_ASSIGN"); return MUL_ASSIGN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 117 "cl.l"
{ Node("/= ","DIV_ASSIGN"); return DIV_ASSIGN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 "cl.l"
{ Node("%= ","MOD_ASSIGN"); return MOD_ASSIGN; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 "cl.l"
{ Node("&= ","AND_ASSIGN"); return AND_ASSIGN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 120 "cl.l"
{ Node("^= ","XOR_ASSIGN"); return XOR_ASSIGN; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 121 "cl.l"
{ Node("|= ","OR_ASSIGN"); return OR_ASSIGN; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 122 "cl.l"
{ Node(">> ","RIGHT_OP"); return RIGHT_OP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 123 "cl.l"
{ Node("<< ","LEFT_OP"); return LEFT_OP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 124 "cl.l"
{ Node("++ ","INC_OP"); return INC_OP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 125 "cl.l"
{ Node("-- ","DEC_OP"); return DEC_OP; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 126 "cl.l"
{ Node("-> ","PTR_OP"); return PTR_OP; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 127 "cl.l"
{ Node("&& ","AND_OP"); return AND_OP; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 128 "cl.l"
{ Node("|| ","OR_OP"); return OR_OP; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 129 "cl.l"
{ Node("<= ","LE_OP"); return LE_OP; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 130 "cl.l"
{ Node(">= ","GE_OP"); return GE_OP; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 131 "cl.l"
{ Node("== ","EQ_OP"); return EQ_OP; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 132 "cl.l"
{ Node("!= ","NE_OP"); return NE_OP; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 133 "cl.l"
{ Node("; ","';'"); return ';'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 134 "cl.l"
{ Node("{ ","'{'"); return '{'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 135 "cl.l"
{ Node("} ","'}'"); return '}'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 136 "cl.l"
{ Node(", ","','"); return ','; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 137 "cl.l"
{ Node(": ","':'"); return ':'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 138 "cl.l"
{ Node("= ","'='"); return '='; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 139 "cl.l"
{ Node("( ","'('"); return '('; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 140 "cl.l"
{ Node(") ","')'"); return ')'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 141 "cl.l"
{ Node("] ","'['"); return '['; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 142 "cl.l"
{ Node("[ ","']'"); return ']'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 143 "cl.l"
{ Node(". ","'.'"); return '.'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 144 "cl.l"
{ Node("& ","'&'"); return '&'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 145 "cl.l"
{ Node("! ","'!'"); return '!'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 146 "cl.l"
{ Node("~ ","'~'"); return '~'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 147 "cl.l"
{ Node("- ","'-'"); return '-'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 148 "cl.l"
{ Node("+ ","'+'"); return '+'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 149 "cl.l"
{ Node("* ","'*'"); return '*'; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 150 "cl.l"
{ Node("/ ","'/'"); return '/'; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 151 "cl.l"
{ Node("% ","'%'"); return '%'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 152 "cl.l"
{ Node("< ","'<'"); return '<'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 153 "cl.l"
{ Node("> ","'>'"); return '>'; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 154 "cl.l"
{ Node("^ ","'^'"); return '^'; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 155 "cl.l"
{ Node("| ","'|'"); return '|'; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 156 "cl.l"
{ Node("? ","'?'"); return '?'; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 158 "cl.l"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 113:
/* rule 113 can match eol */
YY_RULE_SETUP
#line 159 "cl.l"
{nextline(); prev = NULL; printf("\n");}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 160 "cl.l"
{; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 162 "cl.l"
ECHO;
	YY_BREAK
#line 1707 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 405 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 405 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 404);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 162 "cl.l"


int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

static void comment(void)
{
    int c;

    while ((c = input()) != 0){
		if (c == '\n')
		{	
			nextline();
		}
        if (c == '*')
        {
            while ((c = input()) == '*')
                ;

            if (c == '/')
                return;

            if (c == 0)
                break;
        }
	}
    yyerror("unterminated comment");
}

static void prep(void)
{
	int c;
	
	while ((c = input()) != '\n' && (c != 0))
	{;}
	if (c == '\n')
		nextline();
		return;
	if (c == 0)
		yyerror("unterminated preprocessor command");
}

static int check_type(void)
{
	push(&init, NULL, yytext);
	switch (sym_type(yytext))
    {
    case TYPEDEF_NAME:	/* previously defined */
        Node(yytext,"TYPEDEF_NAME");
		return TYPEDEF_NAME;
    case ENUMERATION_CONSTANT:	/* previously defined */
        Node(yytext,"ENUMERATION_CONSTANT");
		return ENUMERATION_CONSTANT;
    default:	/* includes undefined */
        Node(yytext,"IDENTIFIER");
		return IDENTIFIER;
    }
}

